spring.application.name=weather
spring.config.import=application.properties

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}


