CREATE TABLE air_pollutions
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    date DATE,
    city VARCHAR(255)
);

CREATE TABLE categories
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    contaminent_value DOUBLE PRECISION,
    airpollution_id   BIGINT,
    agi_category      VARCHAR(50),
    contaminent       VARCHAR(50)
);

ALTER TABLE categories
    ADD CONSTRAINT fk_categories_air_pollutions
    FOREIGN KEY (airpollution_id)
    REFERENCES air_pollutions (id) ON DELETE CASCADE;
